image: Visual Studio 2017

build_script:
- cmd: vcbuild-ci.bat

clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

artifacts:
  - path: bin\alt-voice.zip
    name: alt-voice binaries

deploy:
- provider: GitHub
  release: alt-voice-$(appveyor_build_version)
  auth_token:
    secure: naIK6AojdsOM0/maAaD+T+C3y7Ak9AsJoLHVgyk9aEVh30MRNX3Hiy11nXU7+/ri
  artifact: /.*/
  draft: true
  on:
    branch: master
